### ISSUE TITLE
Recent month data is not coming

### ISSUE THREAD

**Issue by biswask** [mountainMath/cancensus#135]
Good morning!

I was trying to download the data 14-10-0288-01 from Cansim this morning using the following code:

d=get_cansim("14-10-0288-01", refresh = TRUE, timeout=1000)

The January data is still not here. Can you please take a look and fix the issue?

Thanks in advance,
Keya.

**Comment by biswask** [comment]
Forgot to mention that, last month I faced the same problem and the December data started downloading after 3 hours of LFS data released by Stat Can.

**Comment by biswask** [comment]
And the other thing is, when I download the data using coordinate, the recent month data is coming. But I need to download the whole dataset. Any help will be much appreciated.

**Comment by biswask** [comment]
Hi again,

The January data is coming now (after 1 hour). But we need the data within 15 minutes after the data got released. Is there anything you can do to speed up the process? It's just this month and the last month it is not working. But before that, I was able to download the data with 10 minutes. 

Thanks in advance,
Keya.

**Comment by mountainMath** [comment]
Last month the issue was with StatCan not updating the tables in a timely fashion. Might have been similar this time, did not check. StatCan advised last month that pulling vector data will result in the up-to-date data, whereas downloading tables had problems. Hopefully those problems will get reduced as StatCan works out the kinks in the system at their end.
