### ISSUE TITLE
Give option of retrieving data in wide or long formats

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#154]
Currently,  `get_census()` returns variables in wide format:

```
cancensus::get_census(dataset='CA16', regions=list(CMA="59933"),
                      vectors=c("v_CA16_408","v_CA16_409","v_CA16_410"),
                      level='CSD') %>% glimpse()
Rows: 39
Columns: 13
$ GeoUID                                                                       <chr> "5915001", …
$ Type                                                                         <fct> CSD, CSD, C…
$ `Region Name`                                                                <fct> Langley (DM…
$ `Area (sq km)`                                                               <dbl> 314.76313, …
$ Population                                                                   <dbl> 117285, 258…
$ Dwellings                                                                    <dbl> 43720, 1226…
$ Households                                                                   <dbl> 41982, 1184…
$ CD_UID                                                                       <chr> "5915", "59…
$ PR_UID                                                                       <chr> "59", "59",…
$ CMA_UID                                                                      <chr> "59933", "5…
$ `v_CA16_408: Occupied private dwellings by structural type of dwelling data` <dbl> 41980, 1184…
$ `v_CA16_409: Single-detached house`                                          <dbl> 21690, 2730…
$ `v_CA16_410: Apartment in a building that has five or more storeys`          <dbl> 1100, 40, 6…
```
When working with multiple vector variables it might be preferable in some cases to have these in long format. Frequently I will call `tidyr::gather()` or `pivot_longer()` to collect these variables after retrieval. 

Tidycensus has a parameter `output` that works like this:
```
One of "tidy" (the default) in which each row represents an enumeration unit-variable combination, or "wide" in which each row represents an enumeration unit and the variables are in the columns.
```
And in practice:
```
get_acs(geography = "county", variables = vars, state = "CA", geometry = TRUE, output = "wide")
```

I think this would be pretty easy to add but would require some work to make sure the various utility functions still work with data in long format.

**Comment by mountainMath** [comment]
Yes, I have been thinking about this too. I am not opposed to it, but not convinced it will be generally useful. But that's just speaking from my own experience. 

For {tidycensus} it makes a little more sense because of the `moe` estimates that are hard to deal with (and get dropped) in the wide format. 

For {cancensus} it strikes me a bit as overly forcing *tidy* principles. I do see how it can be useful when not querying geographies, but as soon as geographies are linked in long form becomes very cumbersome. Unless it's for the final stages of an analysis e.g. for facetted mapping.

Especially with the new `across` verb, that makes it easy to manipulate groups of columns, I see little advantage to long form that outweighs the conceptual simplicity of one row = one geographic region.

I think it comes down to how often people are using `pivot_longer` right away. If that's a use case that comes up a lot it might be worth it to facilitate it. Although it is not clear to me what variables should be pivoted. Just the census variables? Including Population, Households and Dwellings? How about area?
