### ISSUE TITLE
Problem with labels and sf format

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#22]
The labels=short options breaks with sf format selected. I added a check to fix this, but am now thinking it would be better to implement the code higher up directly on the dat object. Not sure if that survives the potential merge with the geo data, but that can be dealt with.

**Comment by atheriel** [comment]
If won't survive the merge. Or, at least `inner_join` is not guaranteed to keep attributes, by design. So I think we have to do it at the end.

**Comment by mountainMath** [comment]
How about defining
```
if (format=="sp") {g_data=geos@data} else {g_data=geos}
```
and then operating on g_data without having to check again. That should make it easier to maintain and add other data operations (like renaming the obscure variables that I still need to do).

**Comment by dshkol** [comment]
Initially I had the code higher up and running everything before the merges, but merging with SF purged the attributes. Also, truncating variable names gets more tricky after the SF merge because the SF geometry data contains the same variables. But I just realized that there's a very simple fix to all of this where you do everything higher up in the pipeline, before the merge, and then if format is merge, just reapply the data frame of variables as an attribute, as that is stored locally within the function anyways.

**Comment by mountainMath** [comment]
Addressed with PR https://github.com/mountainMath/cancensus/pull/24
