### ISSUE TITLE
Submission to CRAN

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#45]
My goal is to have this package end up on CRAN eventually. There's still work to do to clean up the vector/geo search and discovery, but I think it's pretty close otherwise. I'm not familiar with the process, so if anyone know what we need to do in order to be approved, please share insights.

**Comment by atheriel** [comment]
Ok, there is a document describing CRAN's policies [here](https://cran.r-project.org/web/packages/policies.html). We seem to abide by them, so from my perspective the most important things are ensuring that:

1) Documentation is in good shape, including Rd files, README, package description, existing vignettes.
2) #28 is resolved, and maybe some other naming issues (I'll submit a separate issue). This is basically to minimize backwards-compatibility issues.
3) API errors are handled "well enough".
4) We pass all `R CMD check` tests (required by CRAN). This can be tested by running `devtools::check()`. There are currently some issues with `dplyr` code and the vignettes that I can work on to make these tests pass.

Once these all look good, there is an automated submission process in `devtools::release()`.

**Comment by atheriel** [comment]
We can turn this into a tracking issue and start using formal milestones, if you'd like.

**Comment by atheriel** [comment]
See also [CRAN's New Submissions Checklist](https://cran.r-project.org/web/packages/new_submission_checklist.html).

**Comment by dshkol** [comment]
Do we need unit testing and code coverage or is that overkill for a relatively slim package?

**Comment by atheriel** [comment]
I think that testing is a good idea in general, but since this package calls out to an external API for most of its fiddly bits, it strikes me as more important to ensure that errors originating in the API are properly propagated down to the user. So no, for this first release I don't think adding unit tests will help all that much.

**Comment by dshkol** [comment]
Updated documentation in #112 

If no one objects I will submit to CRAN this weekend or earlier. CRAN maintainers are on vacation from December 22 onwards, and I would like to have it submitted and accepted/rejected before then so there's time to make fixes during the winter break, if necessary.

**Comment by atheriel** [comment]
Be sure to create a `cran_comments.md` file to track (re-)submission info. I'd suggest using the `devtools::release()` approach, if you hadn't planned to already. And keep in mind that it's just as likely to get rejected for small spelling issues that can be fixed in 30s as anything else -- so you won't necessarily need long to resubmit.

**Comment by atheriel** [comment]
[Hadley's book chapter on CRAN release](http://r-pkgs.had.co.nz/release.html) is a great reference for pretty much everything, btw.

**Comment by dshkol** [comment]
I submitted to CRAN on 12/20, so just waiting for a response now as they are on winter break. 

https://github.com/mountainMath/cancensus/blob/master/cran-comments.md

**Comment by dshkol** [comment]
On CRAN now.
