### ISSUE TITLE
Master Documentation and Examples

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#65]
Issues may not be the best place for this but wanted to let you guys know that I've started working on a comprehensive set of documentation/vignettes to detail `cancensus` usage.  I've been in and out of town recently but over the next week or so I intend to put together this material. 

I see it working best as a three-part document:

* Part 1 : Why cancensus and accessing data
  - Stats Can
  - Background and Censusmapper
  - Data load functions
  -  Data parameters
  -  Working with regions
  - Working with census vectors
  - Spatial formats
* Part 2: Analyzing and Visualizing cancensus data
  - cancensus and tidy data manipulation (dplyr, %>% etc.)
  - Visualizing (non-spatial) Census data
* Part 3: Making maps with cancensus
  - cancensus + sf+ ggplot2
  - cancensus + leaflet

Any suggestions? 

I'm halfway through Part 1, and I'll post them here first when ready. I'm going to be out of town Friday-Monday, but should gradually work towards finishing these by end of next week. 

My plan is to put this series up here as vignettes, but also on a site (good reason to finally finish that rmarkdown+blogdown+hugo site). I think a condensed version would also work well as a submission to Rbloggers, R views, as well as general social media. 

In the meantime, is there anything we still need to do in order to submit to CRAN?

**Comment by atheriel** [comment]
Sorry that I've been absent this week -- I should be able to start contributing again after the weekend. It's good to know you're working on something comprehensive. My only suggestion would be that the longer your document, the fewer readers will finish it. I also what to highlight that we should put together a really eye-catching README culled from the vignettes once they're ready, because I suspect many people will click through to the GitHub page to check out the package. I'm also trying to write a blog post using the package. Rweekly and R-bloggers, and perhaps Reddit, are all good places to post R content if you're into that.

As for CRAN -- for me, I want to resolve #62 (and have unfinished work to do so), work on some unfinished business from #28, and make the documentation look good. After that, we just need to pass `devtools::check()` with no errors, warnings, or notes, change the version to 2.0, and upload the package. I want to caution that CRAN generally allows packages to be updated only once every few months, so my feeling is that we should get as much as we can right the first time. I think we should keep discussion of CRAN submission in #45 if possible, though.

**Comment by dshkol** [comment]
@atheriel Should we re-open #28? What do you feel is outstanding there? I agree, let's keep CRAN talk to #45 - and that we should finalize these small changes, vignettes, etc before submitting. 

Do you want to coordinate on the blog posts, etc, so we don't overlap? I'm pretty looped into the data, open data, academia, etc. communities for these parts, and I think they would really appreciate this tool.

**Comment by dshkol** [comment]
New vignettes have been added and pkgdown documentation ready to go once #103 clears
