### ISSUE TITLE
Default geo_format

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#73]
I am thinking we should change the default geo_format to NA. Had some conversations with people with older R version that could not get `cancensus` to work because

1. they could not or did not want to install a dev version of ggplot and sf, and
2. their R version was too old to install standard gdal to make sp work, and they did not want to upgrade in the middle of an important project

That's probably an extreme case, but I feel we should keep the entry barrier as low as possible. Also, I ran into a couple of bugs in sf/ggplot, so it might still take some time before this matures. So it might be better to let the user explicitly select which geography format they want to work with rather than selecting a default.

Thoughts?

**Comment by dshkol** [comment]
sf/ggplot is in development right now and is due to be implemented in the next CRAN release of ggplot. I don't have a date when to expect that, however, but it's been brought up lots of times in the ggplot and sf communities that this is something to be added as soon as possible.

If I understand what @mountainMath is saying, you would rather that the default behaviour of cancensus be to return data only without geography? In essence, functioning like `get_census_data()` currently does? I'm ok with that so long as we have very clear and robust documentation about including geo formats. 

sp + rgdal have been around for a long time, and I have no idea how anyone would do anything geo-related without it... I'm pretty sure I know who you are talking about with that comment, and I don't really see the need for adapting things to an edge case like that. This person should still be able to use `get_census_data()` instead.

**Comment by atheriel** [comment]
Maybe the right thing to do is change introductory examples to use `get_census_data()` instead, and warn users a bit more at the outset about using geometry data.

**Comment by dshkol** [comment]
You could have a Data only -> Data + Geo flow in the documentation, with full explanation about the SP and SF class geo data available and what is required to use them.

**Comment by dshkol** [comment]
Is it better to introduce `get_census_data` first and work with that before introducing the `get_census` function that comes with geo formats? Or is it better to stick with what we have, in terms of `get_census` being the primary function, but following @mountainMath's suggestion in turning the default geo_format parameter to NA. In this case, there wouldn't even be a need for `get_census_data` anymore.

**Comment by atheriel** [comment]
Another alternative would be to change the internal logic so that sf
remains the default, but it will set geo_format to NA if neither rgdal nor
sf is available (at the moment this is an error).

**Comment by dshkol** [comment]
I think that would catch people off guard when they expect geography returned with their data (as it would work in examples and in documentation) and none is returned. IMO, better to make that more explicit. I would prefer setting default to NA to this, probably.

**Comment by mountainMath** [comment]
I also think setting the default to NA is the way to go. That way users have to be explicit about what geo format they query and there won't be any surprises. I can also add some explanation or an extra button to the CensusMapper API tool, maybe a button where you select if you want just data or also geographies, and which geography, when it generates the R code to copy-paste.

**Comment by atheriel** [comment]
Sounds good to me.

**Comment by dshkol** [comment]
Addressed in #75
